services:
  - type: web
    name: mysite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings